Resolve configure issues for CUDA component.

diff --git a/src/components/cuda/configure b/src/components/cuda/configure
--- a/src/components/cuda/configure
+++ b/src/components/cuda/configure
@@ -271,7 +271,7 @@ PACKAGE_VERSION=
 PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CUDA_VERSION CUDA_INCDIR CUPTI_INCDIR CUPTI_LIBDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CUDA_VERSION CUDA_DIR CUPTI_DIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -798,9 +798,8 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
---with-cuda_incdir=<path> Specify path to CUDA includes
---with-cupti_incdir=<path> Specify path to CuPTI includes
---with-cupti_libdir=<path> Specify path to cupti library
+  --with-cuda-dir=<path>  Specify path to CUDA root directory
+  --with-cupti-dir=<path> Specify path to CuPTI root directory
 
 Some influential environment variables:
   CC          C compiler command
@@ -1246,32 +1245,6 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-
-
-
-# Check whether --with-cuda_incdir or --without-cuda_incdir was given.
-if test "${with_cuda_incdir+set}" = set; then
-  withval="$with_cuda_incdir"
-  CUDA_INCDIR=$withval
-             CFLAGS="$CFLAGS -I$withval"
-else
-  { { echo "$as_me:$LINENO: error: Component requires path to CUDA includes" >&5
-echo "$as_me: error: Component requires path to CUDA includes" >&2;}
-   { (exit 1); exit 1; }; }
-fi;
-
-
-
-# Check whether --with-cupti_incdir or --without-cupti_incdir was given.
-if test "${with_cupti_incdir+set}" = set; then
-  withval="$with_cupti_incdir"
-  CUPTI_INCDIR=$withval
-             CFLAGS="$CFLAGS -I$withval"
-else
-  { { echo "$as_me:$LINENO: error: Component requires path to CuPTI includes" >&5
-echo "$as_me: error: Component requires path to CuPTI includes" >&2;}
-   { (exit 1); exit 1; }; }
-fi;
 
 
 ac_ext=c
@@ -2206,11 +2179,103 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-# Check whether --with-cupti_libdir or --without-cupti_libdir was given.
-if test "${with_cupti_libdir+set}" = set; then
-  withval="$with_cupti_libdir"
-  CUPTI_LIBDIR=$withval
-             LDFLAGS="$LDFLAGS -L$withval -lcupti"
+# Check whether --with-cuda_dir or --without-cuda_dir was given.
+if test "${with_cuda_dir+set}" = set; then
+  withval="$with_cuda_dir"
+  CUDA_DIR=$withval
+		CFLAGS="$CFLAGS -I$withval/include"
+		LDFLAGS="$LDFLAGS -L$withval/lib64 -Wl,-rpath-link -Wl,$withval/lib64"
+
+echo "$as_me:$LINENO: checking for cudaMalloc in -lcudart" >&5
+echo $ECHO_N "checking for cudaMalloc in -lcudart... $ECHO_C" >&6
+if test "${ac_cv_lib_cudart_cudaMalloc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcudart  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char cudaMalloc ();
+int
+main ()
+{
+cudaMalloc ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cudart_cudaMalloc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_cudart_cudaMalloc=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cudart_cudaMalloc" >&5
+echo "${ECHO_T}$ac_cv_lib_cudart_cudaMalloc" >&6
+if test $ac_cv_lib_cudart_cudaMalloc = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBCUDART 1
+_ACEOF
+
+  LIBS="-lcudart $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: CUDA cudart library not found" >&5
+echo "$as_me: error: CUDA cudart library not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+else
+  { { echo "$as_me:$LINENO: error: Component requires path to CUDA root directory" >&5
+echo "$as_me: error: Component requires path to CUDA root directory" >&2;}
+   { (exit 1); exit 1; }; }
+fi;
+
+
+# Check whether --with-cupti_dir or --without-cupti_dir was given.
+if test "${with_cupti_dir+set}" = set; then
+  withval="$with_cupti_dir"
+  CUPTI_DIR=$withval
+		CFLAGS="$CFLAGS -I$withval/include"
+		LDFLAGS="$LDFLAGS -L$CUDA_DIR/lib64 -lcudart  -L$withval/lib64 -lcupti -Wl,-rpath,$CUDA_DIR/lib64  -Wl,-rpath,$withval/lib64"
 
 echo "$as_me:$LINENO: checking for cuptiSubscribe in -lcupti" >&5
 echo $ECHO_N "checking for cuptiSubscribe in -lcupti... $ECHO_C" >&6
@@ -2284,16 +2349,17 @@ _ACEOF
   LIBS="-lcupti $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: libcupti.a not found" >&5
-echo "$as_me: error: libcupti.a not found" >&2;}
+  { { echo "$as_me:$LINENO: error: CuPTI library not found" >&5
+echo "$as_me: error: CuPTI library not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
 else
-  { { echo "$as_me:$LINENO: error: Component requires path to cupti library" >&5
-echo "$as_me: error: Component requires path to cupti library" >&2;}
+  { { echo "$as_me:$LINENO: error: Component requires path to CuPTI root directory" >&5
+echo "$as_me: error: Component requires path to CuPTI root directory" >&2;}
    { (exit 1); exit 1; }; }
 fi;
+
 
 
 nvcc_version=`nvcc -V 2>&1 | tail -n 1 | awk '{printf $5}'`
@@ -2313,7 +2379,6 @@ if test "$major" -eq 4; then
 fi
 
           ac_config_files="$ac_config_files Makefile.cuda"
-
 
 
 
@@ -2960,9 +3025,8 @@ s,@ac_ct_CC@,$ac_ct_CC,;t t
 s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CUDA_VERSION@,$CUDA_VERSION,;t t
-s,@CUDA_INCDIR@,$CUDA_INCDIR,;t t
-s,@CUPTI_INCDIR@,$CUPTI_INCDIR,;t t
-s,@CUPTI_LIBDIR@,$CUPTI_LIBDIR,;t t
+s,@CUDA_DIR@,$CUDA_DIR,;t t
+s,@CUPTI_DIR@,$CUPTI_DIR,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
