Added one more test for libpfm features

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -6177,6 +6177,117 @@ _ACEOF
 
 fi
 
+	echo "$as_me:$LINENO: checking for pfmlib_output_param_t.pfp_pmd_count" >&5
+echo $ECHO_N "checking for pfmlib_output_param_t.pfp_pmd_count... $ECHO_C" >&6
+if test "${ac_cv_member_pfmlib_output_param_t_pfp_pmd_count+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "perfmon/pfmlib.h"
+
+int
+main ()
+{
+static pfmlib_output_param_t ac_aggr;
+if (ac_aggr.pfp_pmd_count)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_pfmlib_output_param_t_pfp_pmd_count=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "perfmon/pfmlib.h"
+
+int
+main ()
+{
+static pfmlib_output_param_t ac_aggr;
+if (sizeof ac_aggr.pfp_pmd_count)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_member_pfmlib_output_param_t_pfp_pmd_count=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_member_pfmlib_output_param_t_pfp_pmd_count=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_member_pfmlib_output_param_t_pfp_pmd_count" >&5
+echo "${ECHO_T}$ac_cv_member_pfmlib_output_param_t_pfp_pmd_count" >&6
+if test $ac_cv_member_pfmlib_output_param_t_pfp_pmd_count = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PFMLIB_OUTPUT_PFP_PMD_COUNT 1
+_ACEOF
+
+fi
+
 	echo "$as_me:$LINENO: checking for pfm_msg_t.pfm_gen_msg.msg_type" >&5
 echo $ECHO_N "checking for pfm_msg_t.pfm_gen_msg.msg_type... $ECHO_C" >&6
 if test "${ac_cv_member_pfm_msg_t_pfm_gen_msg_msg_type+set}" = set; then
@@ -6315,6 +6426,11 @@ _ACEOF
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_PFM_GET_EVENT_DESCRIPTION 1
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_PFMLIB_OUTPUT_PFP_PMD_COUNT 1
 _ACEOF
 
 fi
