Fixed build for ALTIX. This was building with PFM in our directory, but there should be always building with the pfm in /usr. Also allowed configure to detect the altix for when we add the MM timer in the future.
Also, cleaned up the NOTLS build options....It should only have been added
in the Rules files.

aLSO, Added some new code for future --with-pfm --pfm-prefix and perfctr
equivalents to configure. This code is commented out.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PMAPI MAKEVER AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP LN_S SET_MAKE RANLIB ac_ct_RANLIB EGREP LIBOBJS NOTLS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PMAPI MAKEVER AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP LN_S SET_MAKE RANLIB ac_ct_RANLIB EGREP LIBOBJS NOTLS altix LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3251,8 +3251,30 @@ fi
 #      ])
 fi
 if test "$CPU" = "itanium2"; then
+#AC_CHECK_LIB([pfm], [pfm_initialize], [], [
+#      echo "Error, libpfm.a is needed on itanium2!"
+#      exit -1
+#      ])
+echo "$as_me:$LINENO: checking for /etc/sgi-release" >&5
+echo $ECHO_N "checking for /etc/sgi-release... $ECHO_C" >&6
+if test "${ac_cv_file__etc_sgi_release+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/etc/sgi-release"; then
+  ac_cv_file__etc_sgi_release=yes
+else
+  ac_cv_file__etc_sgi_release=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__etc_sgi_release" >&5
+echo "${ECHO_T}$ac_cv_file__etc_sgi_release" >&6
+if test $ac_cv_file__etc_sgi_release = yes; then
 
-echo "$as_me:$LINENO: checking for pfm_initialize in -lpfm" >&5
+	echo "$as_me:$LINENO: checking for pfm_initialize in -lpfm" >&5
 echo $ECHO_N "checking for pfm_initialize in -lpfm... $ECHO_C" >&6
 if test "${ac_cv_lib_pfm_pfm_initialize+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3317,18 +3339,18 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_pfm_pfm_initialize" >&5
 echo "${ECHO_T}$ac_cv_lib_pfm_pfm_initialize" >&6
 if test $ac_cv_lib_pfm_pfm_initialize = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBPFM 1
-_ACEOF
 
-  LIBS="-lpfm $LIBS"
+	altix="-DALTIX"
+	pfm_prefix="/usr"
+else
+
+	altix=""
+	pfm_prefix=""
+fi
+
 
 fi
 
-#AC_CHECK_LIB([pfm], [pfm_initialize], [], [
-#      echo "Error, libpfm.a is needed on itanium2!"
-#      exit -1
-#      ])
 fi
 
 if test "$OS" = "aix"; then
@@ -7332,6 +7354,10 @@ _ACEOF
 #AC_MSG_RESULT($NOTLS)
 
 
+# AC_SUBST(perfctr_prefix)
+# AC_SUBST(perfctr)
+# AC_SUBST(pfm_prefix)
+# AC_SUBST(pfm)
 
 get_bitmode()
 {
@@ -7992,6 +8018,7 @@ s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@NOTLS@,$NOTLS,;t t
+s,@altix@,$altix,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
 
