Override auto-detection of substrate if the user specifies what they want to build with.  This allows building perfctr and perfmon2 PAPI on systems auto-detected as having perf_event support.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5261,12 +5261,14 @@ echo "${ECHO_T}$shlib" >&6
 #          perfctr
 ##################################################
 perfctr=0
+force_perfctr=no
 if test "x$no_cpu_counters" = "x"; then
 
 # Check whether --with-perfctr or --without-perfctr was given.
 if test "${with_perfctr+set}" = set; then
   withval="$with_perfctr"
-  user_specified_interface=perfctr
+  force_perfctr=yes
+            user_specified_interface=perfctr
 	     if test "$arch" != "ppc64"; then
 	     perfctr=6
 	     else
@@ -5672,6 +5674,7 @@ user_specified_interface=no
 old_pfmv2=n
 perfmon=0
 perfmon2=no
+force_perfmon2=no
 
 
 # Check whether --with-perfmon or --without-perfmon was given.
@@ -5679,6 +5682,7 @@ if test "${with_perfmon+set}" = set; then
   withval="$with_perfmon"
   perfmon=$withval
              user_specified_interface=perfmon
+	     force_perfmon2=yes
              perfmon=`echo ${perfmon} | sed 's/^ \t*//;s/ \t*$//'`
              perfmon=`echo ${perfmon} | grep -e '[1-9]\.[0-9][0-9]*'`
              if test "x$perfmon" = "x"; then
@@ -6938,7 +6942,27 @@ echo "$as_me: error: pmc_npmc info returned 0. Determine if the HWPMC module is 
     echo "" >> freebsd-config.h
     echo "#endif" >> freebsd-config.h ;;
   linux)
-    if test "$perf_events" = "yes" ; then
+
+    if test "$force_perf_events" = "yes" ; then
+      MAKEVER="$OS"-pe
+    elif test "$force_perfmon2" = "yes" ; then
+      MAKEVER="$OS"-perfmon2
+    elif test "$force_perfctr" = "yes" ; then
+      case "$CPU" in
+        itanium2|montecito)
+          if test "$bitmode" = "32"; then
+            { { echo "$as_me:$LINENO: error: The bitmode you specified is not supported" >&5
+echo "$as_me: error: The bitmode you specified is not supported" >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+	  MAKEVER="$OS"-pfm-"$CPU"
+	  ;;
+        athlon|opteron|atom|core|core2|p3|p4|i7)
+	        MAKEVER="$OS"-perfctr-x86 ;;
+        POWER5|POWER5+|POWER6|POWER7|PPC970)
+          MAKEVER="$OS"-perfctr-"$CPU" ;;
+     esac
+    elif test "$perf_events" = "yes" ; then
       MAKEVER="$OS"-pe
     elif test "$perfmon2" = "yes" ; then
       MAKEVER="$OS"-perfmon2
