This was a good catch by Dan. 64 bit and 32 bit are extremely sensitive to what configure decides what the cpu is. I have updated this so that its more related to what ARCH says. If arch says x86_64, then default is 64 bit unless bitmode overrides. It arch says x86, then any bitmode other than 32 is no good. This should handle funny things like the core, athlon64 and any funny 64 bit p4 variants that don't show up as an em64t.
Change in Rules.perfctr was to remove a $^

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5635,33 +5635,47 @@ echo "$as_me: error: The bitmode you specified is not supported" >&2;}
    else
 		    MAKEVER="$OS"-pfm-"$CPU"
 		 fi ;;
-            opteron|em64t)
-                 if test "${with_bitmode}" = "32"; then
-                 	MAKEVER="$OS"-perfctr-"$CPU""-32bit"
-                 else
+            opteron|em64t|athlon|p4|p3)
+		if test "$arch" = "x86_64"; then
 			if test "$perfctr" != "no"; then
+				if test "${with_bitmode}" = "32"; then
+				 	MAKEVER="$OS"-perfctr-"$CPU""-32bit"
+				else
+					MAKEVER="$OS"-perfctr-"$CPU"
+				fi
+			elif test "$perfmon" != "no"; then
+				MAKEVER="$OS"-perfmon2
+			else
+				MAKEVER="$OS"-perfctr-"$CPU"
+			fi
+		else
+		        if test "${bitmode}" = "64"; then
+			   { { echo "$as_me:$LINENO: error: The bitmode you specified is not supported" >&5
+echo "$as_me: error: The bitmode you specified is not supported" >&2;}
+   { (exit 1); exit 1; }; }
+			elif test "$perfctr" != "no"; then
 			   MAKEVER="$OS"-perfctr-"$CPU"
-		        elif test "$perfmon" != "no"; then
+			elif test "$perfmon" != "no"; then
 			   MAKEVER="$OS"-perfmon2
 			else
 			   MAKEVER="$OS"-perfctr-"$CPU"
 			fi
-		 fi
+		fi
 		 ;;
-            athlon|p4|p3|p2)
-                 if test "${bitmode}" = "64"; then
+            p2)
+                if test "${bitmode}" = "64"; then
                    { { echo "$as_me:$LINENO: error: The bitmode you specified is not supported" >&5
 echo "$as_me: error: The bitmode you specified is not supported" >&2;}
    { (exit 1); exit 1; }; }
-                 fi
+                fi
 		if test "$perfctr" != "no"; then
 		   MAKEVER="$OS"-perfctr-"$CPU"
 		elif test "$perfmon" != "no"; then
 		   MAKEVER="$OS"-perfmon2
 		else
 		   MAKEVER="$OS"-perfctr-"$CPU"
-   fi
-   ;;
+		fi
+		;;
             PPC32)
                  if test "${bitmode}" = "64"; then
                    { { echo "$as_me:$LINENO: error: The bitmode you specified is not supported" >&5
@@ -5761,7 +5775,7 @@ fi
 if test "$OS" = "linux" -a "$bitmode" = "64"; then
    if test "$arch" = "mips64" -o "$arch" = "ppc64" -o "$arch" = "x86_64"; then
       if test "$libdir" = '${exec_prefix}/lib'; then
-        $libdir='${exec_prefix}/lib64'
+        libdir='${exec_prefix}/lib64'
       fi
    fi
 fi
