add checking for per thread timer

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -311,7 +311,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PMAPI MAKEVER AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP LN_S SET_MAKE RANLIB ac_ct_RANLIB PAPI_DATADIR EGREP LIBOBJS NOTLS altix PMINIT LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS PMAPI MAKEVER AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP LN_S SET_MAKE RANLIB ac_ct_RANLIB PAPI_DATADIR EGREP LIBOBJS NOTLS NOPTTIMER altix PMINIT LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -847,6 +847,7 @@ Optional Packages:
   --with-bitmode=32/64       Specify bit mode of library
   --with-pmapi=<path>     Specify path of pmapi on aix system
   --with-tls=<no>         To disable tls support
+  --with-PTtimer=<no>         To disable PTtimer support
 
 Some influential environment variables:
   CC          C compiler command
@@ -7679,6 +7680,146 @@ _ACEOF
 
 
 
+
+# Check whether --with-PTtimer or --without-PTtimer was given.
+if test "${with_PTtimer+set}" = set; then
+  withval="$with_PTtimer"
+  PTtimer=$withval
+else
+  PTtimer=yes
+
+fi;
+case "$PTtimer" in
+   yes)
+      #       NOTLS="" ;;
+                        with_PTtimer="__thread"
+      echo "$as_me:$LINENO: checking for working per-thread timer" >&5
+echo $ECHO_N "checking for working per-thread timer... $ECHO_C" >&6
+      #echo $with_PTtimer
+      if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+             #include <sys/times.h>
+             #include <assert.h>
+             #include <stdio.h>
+             #include <sys/types.h>
+             #include <unistd.h>
+             #include <sys/unistd.h>
+             #include <syscall.h>
+
+             #if ! defined( SYS_gettid )
+             #define SYS_gettid 1105
+             #endif
+
+             long threadone = 0;
+             long threadtwo = 0;
+
+             int gettid() {
+               return syscall( SYS_gettid );
+             }
+
+             int doThreadOne( void * v ) {
+               struct tms tm;
+               int status;
+
+               sleep( 10 );
+
+               status = times( & tm );
+               assert( status != -1 );
+               threadone = tm.tms_utime;
+
+               return 0;
+             }
+
+             int doThreadTwo( void * v ) {
+               struct tms tm;
+               long i;
+               int status;
+
+               for( i = 0; i < 0xFFFFFFFF; ++i ) { ; }
+
+               status = times( & tm );
+               assert( status != -1 );
+
+               threadtwo = tm.tms_utime;
+               return 0;
+             }
+
+             int main( int argc, char ** argv ) {
+               int status;
+               pthread_t threadOne, threadTwo;
+
+               status = pthread_create( & threadOne, NULL, doThreadOne, NULL );
+               assert( status == 0 );
+               status = pthread_create( & threadTwo, NULL, doThreadTwo, NULL );
+               assert( status == 0 );
+
+
+               status = pthread_join( threadTwo, NULL );
+               assert( status == 0 );
+               status = pthread_join( threadOne, NULL );
+               assert( status == 0 );
+
+	           return (threadone == threadtwo);
+             }
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+
+            echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+            with_PTtimer=pthread
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+     if test "x$with_PTtimer" = "xpthread"; then
+        NOPTTIMER="-DHAS_PER_PROCESS_TIMES"
+     fi
+     ;;
+
+ no)
+             NOPTTIMER="-DHAS_PER_PROCESS_TIMES" ;;
+ esac
+
+#AC_MSG_RESULT($NOPTTIMER)
+
+
+
+
 # AC_SUBST(perfctr_prefix)
 # AC_SUBST(perfctr)
 # AC_SUBST(pfm_prefix)
@@ -8344,6 +8485,7 @@ s,@PAPI_DATADIR@,$PAPI_DATADIR,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@NOTLS@,$NOTLS,;t t
+s,@NOPTTIMER@,$NOPTTIMER,;t t
 s,@altix@,$altix,;t t
 s,@PMINIT@,$PMINIT,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
