Runtime test for ALTIX. Fix for systems that SGI is shipping...

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -3825,10 +3825,63 @@ echo "$as_me:$LINENO: result: $ac_cv_file_sn_mmtimer_h" >&5
 echo "${ECHO_T}$ac_cv_file_sn_mmtimer_h" >&6
 if test $ac_cv_file_sn_mmtimer_h = yes; then
 
-		altix="-DALTIX"
+		if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&5
+echo "$as_me: error: cannot run test program while cross compiling
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
 else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-		altix=""
+#include <unistd.h>
+#include <fcntl.h>
+#include <errno.h>
+#include <stdlib.h>
+#include <sys/ioctl.h>
+#include <sn/mmtimer.h>
+
+int main()
+{
+  int offset;
+  int fd;
+
+     if((fd = open(MMTIMER_FULLNAME, O_RDONLY)) == -1) {
+       exit(1);
+     }
+     if ((offset = ioctl(fd, MMTIMER_GETOFFSET, 0)) == -ENOSYS) {
+       exit(1);
+     }
+     close(fd);
+     exit(0);
+}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  altix="-DALTIX"
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 fi
 
 fi
